apiVersion: v1
kind: Service
metadata:
  name: nginx-service-loadbalancer
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  type: LoadBalancer
  ports:
  - name: http
    port: 8080
    targetPort: 80
    protocol: TCP
    